//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Runtime.CompilerServices;
using System.Windows.Forms;

namespace ScreenToGif.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool showCursor {
            get {
                return ((bool)(this["showCursor"]));
            }
            set {
                this["showCursor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool allowEdit {
            get {
                return ((bool)(this["allowEdit"]));
            }
            set {
                this["allowEdit"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool saveLocation {
            get {
                return ((bool)(this["saveLocation"]));
            }
            set {
                this["saveLocation"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("15")]
        public int maxFps {
            get {
                return ((int)(this["maxFps"]));
            }
            set {
                this["maxFps"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("500, 280")]
        public Size size {
            get {
                return ((Size)(this["size"]));
            }
            set {
                this["size"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("F8")]
        public Keys stopKey {
            get {
                return ((Keys)(this["stopKey"]));
            }
            set {
                this["stopKey"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("F7")]
        public Keys startPauseKey {
            get {
                return ((Keys)(this["startPauseKey"]));
            }
            set {
                this["startPauseKey"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool modernStyle {
            get {
                return ((bool)(this["modernStyle"]));
            }
            set {
                this["modernStyle"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("10")]
        public int quality {
            get {
                return ((int)(this["quality"]));
            }
            set {
                this["quality"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool loop {
            get {
                return ((bool)(this["loop"]));
            }
            set {
                this["loop"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool encodingCustom {
            get {
                return ((bool)(this["encodingCustom"]));
            }
            set {
                this["encodingCustom"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2")]
        public int repeatCount {
            get {
                return ((int)(this["repeatCount"]));
            }
            set {
                this["repeatCount"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool repeatForever {
            get {
                return ((bool)(this["repeatForever"]));
            }
            set {
                this["repeatForever"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("detect")]
        public string language {
            get {
                return ((string)(this["language"]));
            }
            set {
                this["language"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("")]
        public string folder {
            get {
                return ((string)(this["folder"]));
            }
            set {
                this["folder"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool preStart {
            get {
                return ((bool)(this["preStart"]));
            }
            set {
                this["preStart"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool paintTransparent {
            get {
                return ((bool)(this["paintTransparent"]));
            }
            set {
                this["paintTransparent"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("LimeGreen")]
        public Color transparentColor {
            get {
                return ((Color)(this["transparentColor"]));
            }
            set {
                this["transparentColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool showFinished {
            get {
                return ((bool)(this["showFinished"]));
            }
            set {
                this["showFinished"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool fullscren {
            get {
                return ((bool)(this["fullscren"]));
            }
            set {
                this["fullscren"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool snapshot {
            get {
                return ((bool)(this["snapshot"]));
            }
            set {
                this["snapshot"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ShowGrid {
            get {
                return ((bool)(this["ShowGrid"]));
            }
            set {
                this["ShowGrid"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Segoe UI, 9pt")]
        public Font fontInsertText {
            get {
                return ((Font)(this["fontInsertText"]));
            }
            set {
                this["fontInsertText"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color forecolorInsertText {
            get {
                return ((Color)(this["forecolorInsertText"]));
            }
            set {
                this["forecolorInsertText"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Segoe UI, 9pt")]
        public Font fontTitleFrame {
            get {
                return ((Font)(this["fontTitleFrame"]));
            }
            set {
                this["fontTitleFrame"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("White")]
        public Color forecolorTitleFrame {
            get {
                return ((Color)(this["forecolorTitleFrame"]));
            }
            set {
                this["forecolorTitleFrame"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color backcolorTitleFrame {
            get {
                return ((Color)(this["backcolorTitleFrame"]));
            }
            set {
                this["backcolorTitleFrame"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("70")]
        public int redFilter {
            get {
                return ((int)(this["redFilter"]));
            }
            set {
                this["redFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("126")]
        public int greenFilter {
            get {
                return ((int)(this["greenFilter"]));
            }
            set {
                this["greenFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("200")]
        public int blueFilter {
            get {
                return ((int)(this["blueFilter"]));
            }
            set {
                this["blueFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("255")]
        public int alphaFilter {
            get {
                return ((int)(this["alphaFilter"]));
            }
            set {
                this["alphaFilter"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool fullscreen {
            get {
                return ((bool)(this["fullscreen"]));
            }
            set {
                this["fullscreen"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool showMouseClick {
            get {
                return ((bool)(this["showMouseClick"]));
            }
            set {
                this["showMouseClick"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool fontSizeAsPercentage {
            get {
                return ((bool)(this["fontSizeAsPercentage"]));
            }
            set {
                this["fontSizeAsPercentage"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Segoe UI, 14pt, style=Bold")]
        public Font fontCaption {
            get {
                return ((Font)(this["fontCaption"]));
            }
            set {
                this["fontCaption"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("White")]
        public Color fontCaptionColor {
            get {
                return ((Color)(this["fontCaptionColor"]));
            }
            set {
                this["fontCaptionColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Far")]
        public StringAlignment captionVerticalAlign {
            get {
                return ((StringAlignment)(this["captionVerticalAlign"]));
            }
            set {
                this["captionVerticalAlign"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Center")]
        public StringAlignment captionHorizontalAlign {
            get {
                return ((StringAlignment)(this["captionHorizontalAlign"]));
            }
            set {
                this["captionHorizontalAlign"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.2")]
        public float fontCaptionPercentage {
            get {
                return ((float)(this["fontCaptionPercentage"]));
            }
            set {
                this["fontCaptionPercentage"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color captionOutlineColor {
            get {
                return ((Color)(this["captionOutlineColor"]));
            }
            set {
                this["captionOutlineColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2.5")]
        public float captionOutlineThick {
            get {
                return ((float)(this["captionOutlineThick"]));
            }
            set {
                this["captionOutlineThick"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool captionUseHatch {
            get {
                return ((bool)(this["captionUseHatch"]));
            }
            set {
                this["captionUseHatch"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Red")]
        public Color captionHatchColor {
            get {
                return ((Color)(this["captionHatchColor"]));
            }
            set {
                this["captionHatchColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("NarrowVertical")]
        public HatchStyle captionHatch {
            get {
                return ((HatchStyle)(this["captionHatch"]));
            }
            set {
                this["captionHatch"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool captionUseOutline {
            get {
                return ((bool)(this["captionUseOutline"]));
            }
            set {
                this["captionUseOutline"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color freeDrawColor {
            get {
                return ((Color)(this["freeDrawColor"]));
            }
            set {
                this["freeDrawColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("9")]
        public int freeDrawBrush {
            get {
                return ((int)(this["freeDrawBrush"]));
            }
            set {
                this["freeDrawBrush"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("9")]
        public int freeDrawEraser {
            get {
                return ((int)(this["freeDrawEraser"]));
            }
            set {
                this["freeDrawEraser"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color borderColor {
            get {
                return ((Color)(this["borderColor"]));
            }
            set {
                this["borderColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2")]
        public float borderThickness {
            get {
                return ((float)(this["borderThickness"]));
            }
            set {
                this["borderThickness"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool showHighDpiWarn {
            get {
                return ((bool)(this["showHighDpiWarn"]));
            }
            set {
                this["showHighDpiWarn"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public Color progressColor {
            get {
                return ((Color)(this["progressColor"]));
            }
            set {
                this["progressColor"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool progressUseHatch {
            get {
                return ((bool)(this["progressUseHatch"]));
            }
            set {
                this["progressUseHatch"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Percent75")]
        public HatchStyle progressHatch {
            get {
                return ((HatchStyle)(this["progressHatch"]));
            }
            set {
                this["progressHatch"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool progressThickAsPercentage {
            get {
                return ((bool)(this["progressThickAsPercentage"]));
            }
            set {
                this["progressThickAsPercentage"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5")]
        public float progressThickness {
            get {
                return ((float)(this["progressThickness"]));
            }
            set {
                this["progressThickness"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.03")]
        public float progressThickPercentage {
            get {
                return ((float)(this["progressThickPercentage"]));
            }
            set {
                this["progressThickPercentage"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("B")]
        public char progressPosition {
            get {
                return ((char)(this["progressPosition"]));
            }
            set {
                this["progressPosition"] = value;
            }
        }
    }
}
